=== osmarAnt/ordinario-ftw/xsd/armaduras.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="armaduras">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pieza" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nombre"/>
              <xs:element type="xs:string" name="tipo"/>
              <xs:element type="xs:byte" name="defensa"/>
              <xs:element type="xs:byte" name="fuego"/>
              <xs:element type="xs:byte" name="agua"/>
              <xs:element type="xs:byte" name="rayo"/>
              <xs:element type="xs:byte" name="hielo"/>
              <xs:element type="xs:byte" name="dragon"/>
              <xs:element type="xs:string" name="habilidad"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== osmarAnt/ordinario-ftw/xml/armaduras.xml
<?xml version="1.0" encoding="UTF-8"?>
<armaduras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/armaduras.xsd">
    <pieza>
        <nombre>Casco Rathalos</nombre>
        <tipo>Casco</tipo>
        <defensa>32</defensa>
        <fuego>3</fuego>
        <agua>-2</agua>
        <rayo>1</rayo>
        <hielo>-1</hielo>
        <dragon>-3</dragon>
        <habilidad>Ataque</habilidad>
    </pieza>

    <pieza>
        <nombre>Pechera Rathalos</nombre>
        <tipo>Pechera</tipo>
        <defensa>34</defensa>
        <fuego>3</fuego>
        <agua>-2</agua>
        <rayo>1</rayo>
        <hielo>-1</hielo>
        <dragon>-3</dragon>
        <habilidad>Punto débil</habilidad>
    </pieza>

    <pieza>
        <nombre>Guantes Rathalos</nombre>
        <tipo>Guantes</tipo>
        <defensa>30</defensa>
        <fuego>3</fuego>
        <agua>-2</agua>
        <rayo>1</rayo>
        <hielo>-1</hielo>
        <dragon>-3</dragon>
        <habilidad>Ataque</habilidad>
    </pieza>

    <pieza>
        <nombre>Cintura Rathalos</nombre>
        <tipo>Cintura</tipo>
        <defensa>31</defensa>
        <fuego>3</fuego>
        <agua>-2</agua>
        <rayo>1</rayo>
        <hielo>-1</hielo>
        <dragon>-3</dragon>
        <habilidad>Resistencia al fuego</habilidad>
    </pieza>

    <pieza>
        <nombre>Botas Rathalos</nombre>
        <tipo>Botas</tipo>
        <defensa>29</defensa>
        <fuego>3</fuego>
        <agua>-2</agua>
        <rayo>1</rayo>
        <hielo>-1</hielo>
        <dragon>-3</dragon>
        <habilidad>Salto</habilidad>
    </pieza>
</armaduras>
